service: image-analyzer
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - rekognition:DetectLabels
      Resource: "*"
    - Effect: "Allow"
      Action:
        - translate:TranslateText
      Resource: "*"


functions:
  image-analysis:
    handler: index.main
    events:
      - httpApi:
          path: /analyze
          method: get
